name: CI/CD Pipeline for React App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  docker:
    runs-on: ['self-hosted', 'Linux', 'X64', 'react']
    needs: build

    steps:
      - name: Stop Docker container
        run: sudo docker stop react-container || true

      - name: Delete old Docker images & container
        run: |
          sudo docker rm react-container || true
          sudo docker rmi react-image || true

      - name: Build Docker image
        run: sudo docker build -t react-image .

      - name: Run Docker container
        run: sudo docker run -d --name react-container -p 3000:3000 react-image
