name:  Ci/ Cd React App

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ['self-hosted', 'Linux', 'X64', 'react' ]

    steps:
    - uses: actions/checkout@v2
    #   with:
    #       node-version: '20.11.1'

    #  # Display npm version
    # - name: Display npm version
    #   run: npm --version"
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '16'
          cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Stop Docker container
      run: docker stop my-container || true

    - name: Delete old Docker images & container
      run: |
          docker rm my-container || true
          docker rmi my-image:latest || true

    - name: Build Docker image
      run: docker build -t my-image .

    - name: Run Docker container
      run: docker run -d --name my-container -p 3000:3000 my-image
